### ISSUE TITLE
Handle special characters in incoming query string to support searching for DOIs

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-finder#11]
We can expect people to submitting URLs and URIs, and also DOIs, to the search endpoint:

https://o2r.uni-muenster.de/api/v1/search?q=10.5555%2F12345678

Currently this returns an error:

```json
failed_shards": [

    {
        "shard": 0,
        "index": "o2r",
        "node": "XMeUHWUmRyepQQbbDdRXeA",
        "reason": {
            "type": "query_shard_exception",
            "reason": "Failed to parse query [10.5555/12345678]",
            "index_uuid": "AWf5E-1_TrmdyKneJHYsnA",
            "index": "o2r",
            "caused_by": {
                "type": "parse_exception",
                "reason": "Cannot parse '10.5555/12345678': Lexical error at line 1, column 17.  Encountered: <EOF> after : \"/12345678\"",
                "caused_by": {
                    "type": "token_mgr_error",
                    "reason": "Lexical error at line 1, column 17.  Encountered: <EOF> after : \"/12345678\""
                }
            }
        }
    }

]
```

This should be handled by finder, ideally by supporting the search for DOIs.

**Comment by LukasLohoff** [comment]
For special characters we might need a custom analyzer, see https://discuss.elastic.co/t/how-to-index-special-characters-and-search-those-special-characters-in-elasticsearch/42506/2

I think DOAJ also uses elasticsearch, and they support searching for DOIs: https://doaj.org/api/v1/docs
