### ISSUE TITLE
Only index o2r metadata in Elasticsearch

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-finder#17]
![image](https://user-images.githubusercontent.com/1325054/33712958-8fd968e8-db49-11e7-9e68-d54713c0b9d7.png)

Reasons:

- raw metadata is not "checked"
- zenodo metadata may only contain what is already in o2r metadata (nothing is missing)
- full text should still be indexed

@7048730 Can you confirm this? Do you see any reason to index more than just the o2r metadata, i.e. should the raw metadata be "searchable"?

**Comment by 7048730** [comment]
yes, go for o2r md
