### ISSUE TITLE
Evaluate golang

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-finder#2]
- https://github.com/go-mgo/mgo/tree/v2 and http://labix.org/mgo
- https://github.com/golang/go/wiki/LearnServerProgramming
  - https://thewhitetulip.gitbooks.io/webapp-with-golang-anti-textbook/content/content/8.0buildingAPI.html
  - https://golang.org/pkg/encoding/json/
  - https://golang.org/pkg/log/
- frameworks
  - https://www.reddit.com/r/golang/comments/252wjh/are_you_using_golang_for_webapi_development_what/
  - https://goji.io/ (start with this!)
  - http://www.gorillatoolkit.org/
  - https://echo.labstack.com/
- https://blog.codeship.com/making-the-switch-from-node-js-to-golang/
- **https://blog.golang.org/context** (basically a template!)
- mongodb & search
  - https://docs.mongodb.com/manual/core/index-text/
  - https://godoc.org/gopkg.in/mgo.v2#Collection.Find
  - https://www.compose.com/articles/full-text-search-with-mongodb-and-node-js/
  - http://stackoverflow.com/questions/23761689/how-to-do-text-search-in-mgo

**Important**: Using golang is not about performance, but about trying out sth. new :smile:

**Comment by thewhitetulip** [comment]
@nuest I'd suggest reading 

https://github.com/thewhitetulip/web-dev-golang-anti-textbook/blob/master/manuscript/8.0buildingAPI.md

instead of the gitbooks, because I am not going to use Gitbooks after maybe a month. The book is going to be available on Leanpub only, as PDF, ePub or Mobi.

**Comment by nuest** [comment]
Thanks for the pointer!

On a different note: Do you have a hint about a markdown-based way to write books that look good as PDFs and have complex sections, etc., and is not bookdown?

**Comment by thewhitetulip** [comment]
I use markdown. I can assure you they look 

what do you mean by complex sections? I would suggest go ahead with leanpub.com

I am placing my book there, https://leanpub.com/antitextbookGo/ 

Leanpub is better than gitbooks

Check this https://leanpub.com/help/manual
