### ISSUE TITLE
Numerous finder logs

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-finder#23]
After starting the platform, the finder logs drive crazy giving lots and lots of logs as shown in the screenshot. This makes it hard to see logs from the other services so I usually miss the debug logs of my own service and have to restart the entire platform.
However, the platform works fine.
![bildschirmfoto vom 2018-05-29 09-35-51](https://user-images.githubusercontent.com/2863409/40644942-22a8299e-6325-11e8-83e2-a6ee9e7db983.png)

**Comment by nuest** [comment]
Use `docker logs` to only look at the logs of your service.

Do the extensive logs occur at the beginning or also after Elasticsearch is fully started?

**Comment by MarkusKonk** [comment]
Crap! I Forgot to set `sudo sysctl -q -w vm.max_map_count=262144`
